version: "3.7"
services:
  web:
    image: "shortener:1.0"
    ports:
      - 8080:8080
    environment:
      - SERVERPORT=8080
      - URLDB=redis # set 'redis' or 'mongo' here

      # redis env variables. set URLDB=redis
      - REDISURL=redis://172.28.1.2:6379 
      - REDISTIMEOUT=5 

      # mongo env variables. set URLDB=mongo
      - MONGOURL=mongodb://root:example@172.28.1.3:27017
      - MONGODB=redirection
      - MONGOTIMEOUT=5
    depends_on:
      - redis_db
    networks:
      node_net:
        ipv4_address: 172.28.1.1

        
  redis_db:
    image: "redis:alpine"
    container_name: redis_db
    command: redis-server 
    ports:
      - 6379:6379
    networks:
      node_net:
        ipv4_address: 172.28.1.2  


  mongo:
    image: mongo:3.6-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      node_net:
        ipv4_address: 172.28.1.3

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16    