version: "3.7"
services:
  postgres:
    image: postgres:13.1
    #restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports: 
      - 5432:5432
    networks:
      node_net:
        ipv4_address: 172.28.1.5

  pgadmin:
    image: dpage/pgadmin4
    #restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@m.ru
      PGADMIN_DEFAULT_PASSWORD: "###123456"
    depends_on:
      - postgres
    networks:
      node_net:
        ipv4_address: 172.28.1.6

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16    